// Generated by scripts/generate_event_codes.py in ogd-standards from the event standard.
// Do not edit by hand. Regenerate it when the standard changes.

namespace OGD {

    /// <summary>
    /// Event codes from the OpenGameData event standard, grouped by category and family.
    /// Game-specific events can use the X900-X999 codes of any block, or the 9000 block.
    /// </summary>
    static public class OGDEvents {

        static public class Meta {

            static public class ApplicationLifecycle {
                /// <summary>The application is launched or started.</summary>
                public const int ApplicationLaunched = 1000;
                /// <summary>The application is closed or terminated.</summary>
                public const int ApplicationTerminated = 1001;
                /// <summary>The application becomes the active foreground application.</summary>
                public const int ApplicationForegrounded = 1002;
                /// <summary>The application leaves the foreground.</summary>
                public const int ApplicationBackgrounded = 1003;
            }

            static public class SessionLifecycle {
                /// <summary>A gameplay session begins.</summary>
                public const int SessionStarted = 1100;
                /// <summary>The gameplay session is paused.</summary>
                public const int SessionPaused = 1101;
                /// <summary>A paused gameplay session resumes.</summary>
                public const int SessionResumed = 1102;
                /// <summary>The gameplay session ends.</summary>
                public const int SessionEnded = 1103;
                /// <summary>The gameplay session is reset.</summary>
                public const int SessionReset = 1104;
            }

            static public class MenuApplicationNavigation {
                /// <summary>The player opens the main application menu.</summary>
                public const int OpenMainMenu = 1200;
                /// <summary>The player closes the main application menu.</summary>
                public const int CloseMainMenu = 1201;
                /// <summary>The player moves between application-level menu screens without selecting an option.</summary>
                public const int NavigateMenuScreen = 1202;
                /// <summary>The player returns to the previous menu screen.</summary>
                public const int ReturnToPreviousMenu = 1203;
                /// <summary>The player selects an application-level menu option.</summary>
                public const int SelectMenuOption = 1204;
            }

            static public class SettingsConfiguration {
                /// <summary>The player opens the settings screen.</summary>
                public const int OpenSettings = 1300;
                /// <summary>The player changes a setting value.</summary>
                public const int ChangeSetting = 1301;
                /// <summary>Settings are reset to defaults.</summary>
                public const int ResetSettings = 1302;
                /// <summary>The settings screen is closed.</summary>
                public const int CloseSettings = 1303;
            }

            static public class ProfileIdentity {
                /// <summary>A player profile is selected.</summary>
                public const int SelectProfile = 1400;
                /// <summary>A player logs in.</summary>
                public const int Login = 1401;
                /// <summary>A player logs out.</summary>
                public const int Logout = 1402;
                /// <summary>A new player profile is created.</summary>
                public const int CreateProfile = 1403;
                /// <summary>A player profile is deleted.</summary>
                public const int DeleteProfile = 1404;
            }

            static public class LoadingApplicationTransitions {
                /// <summary>Application-level loading begins.</summary>
                public const int StartLoading = 1500;
                /// <summary>Application-level loading completes.</summary>
                public const int LoadingComplete = 1501;
                /// <summary>A non-gameplay application transition begins.</summary>
                public const int StartApplicationTransition = 1502;
                /// <summary>A non-gameplay application transition completes.</summary>
                public const int CompleteApplicationTransition = 1503;
            }

            static public class Matchmaking {
                /// <summary>The player enters a matchmaking process to be placed into a gameplay session.</summary>
                public const int EnterMatchmaking = 1600;
                /// <summary>The player leaves a matchmaking process before being placed into a session.</summary>
                public const int ExitMatchmaking = 1601;
                /// <summary>The system identifies a compatible match for the player.</summary>
                public const int MatchmakingMatchFound = 1602;
                /// <summary>The player is assigned to a gameplay session or pre-game lobby.</summary>
                public const int MatchmakingAssignment = 1603;
                /// <summary>The matchmaking process ends without forming a match.</summary>
                public const int MatchmakingTimeout = 1604;
            }
        }

        static public class NarrativeCommunication {

            static public class Narration {
                /// <summary>Narration sequence becomes available/active.</summary>
                public const int EnterNarration = 2001;
                /// <summary>Narration sequence is exited and no longer active.</summary>
                public const int ExitNarration = 2002;
                /// <summary>Narration ends before completion due to interruption or quit.</summary>
                public const int AbandonNarration = 2003;
                /// <summary>Narration begins advancing/playing.</summary>
                public const int StartNarration = 2010;
                /// <summary>Narration reaches its intended end without skipping/abandoning.</summary>
                public const int CompleteNarration = 2011;
                /// <summary>Narration display is cleared or no longer available.</summary>
                public const int ClearNarration = 2012;
                /// <summary>Narration advances to the next unit (player or system driven).</summary>
                public const int AdvanceNarration = 2013;
                /// <summary>Narration is skipped to the end (or past remaining content).</summary>
                public const int SkipNarration = 2014;
            }

            static public class Dialog {
                /// <summary>Dialog sequence becomes available/active.</summary>
                public const int EnterDialog = 2101;
                /// <summary>Dialog sequence is exited and no longer active.</summary>
                public const int ExitDialog = 2102;
                /// <summary>Dialog ends before completion due to interruption or quit.</summary>
                public const int AbandonDialog = 2103;
                /// <summary>Dialog begins advancing/playing.</summary>
                public const int StartDialog = 2110;
                /// <summary>Dialog reaches its intended end (animation/playback finished).</summary>
                public const int CompleteDialog = 2111;
                /// <summary>Dialog display is cleared or no longer available.</summary>
                public const int ClearDialog = 2112;
                /// <summary>Dialog advances to the next unit (typically player action).</summary>
                public const int AdvanceDialog = 2113;
                /// <summary>Dialog is skipped to the end (typically player action).</summary>
                public const int SkipDialog = 2114;
                /// <summary>Dialog choice options are displayed to the player.</summary>
                public const int ChoicesDisplayed = 2115;
                /// <summary>A dialog choice is selected.</summary>
                public const int ChoiceSelected = 2116;
                /// <summary>Player begins a free-text or open response input.</summary>
                public const int FreeResponseInitiated = 2117;
                /// <summary>Player submits a dialog response (choice or free response).</summary>
                public const int SubmitResponse = 2118;
            }

            static public class Tutorialization {
                /// <summary>Tutorial sequence becomes available/active.</summary>
                public const int EnterTutorial = 2201;
                /// <summary>Tutorial sequence is exited and no longer active.</summary>
                public const int ExitTutorial = 2202;
                /// <summary>Tutorial ends before completion due to interruption or quit.</summary>
                public const int AbandonTutorial = 2203;
                /// <summary>Tutorial begins advancing/playing.</summary>
                public const int StartTutorial = 2210;
                /// <summary>Tutorial reaches its intended end.</summary>
                public const int CompleteTutorial = 2211;
                /// <summary>Tutorial display is cleared or no longer available.</summary>
                public const int ClearTutorial = 2212;
                /// <summary>Tutorial advances to the next unit.</summary>
                public const int AdvanceTutorial = 2213;
                /// <summary>Tutorial is skipped to the end.</summary>
                public const int SkipTutorial = 2214;
            }

            static public class PositiveFeedback {
                /// <summary>Positive feedback sequence begins.</summary>
                public const int StartPositiveFeedback = 2310;
                /// <summary>Positive feedback sequence completes naturally.</summary>
                public const int CompletePositiveFeedback = 2311;
                /// <summary>Positive feedback display is cleared or no longer available.</summary>
                public const int ClearPositiveFeedback = 2312;
                /// <summary>Positive feedback advances to the next unit (if multi-part).</summary>
                public const int AdvancePositiveFeedback = 2313;
                /// <summary>Positive feedback is skipped to the end.</summary>
                public const int SkipPositiveFeedback = 2314;
            }

            static public class NegativeFeedback {
                /// <summary>Negative feedback sequence begins.</summary>
                public const int StartNegativeFeedback = 2410;
                /// <summary>Negative feedback sequence completes naturally.</summary>
                public const int CompleteNegativeFeedback = 2411;
                /// <summary>Negative feedback display is cleared or no longer available.</summary>
                public const int ClearNegativeFeedback = 2412;
                /// <summary>Negative feedback advances to the next unit (if multi-part).</summary>
                public const int AdvanceNegativeFeedback = 2413;
                /// <summary>Negative feedback is skipped to the end.</summary>
                public const int SkipNegativeFeedback = 2414;
            }

            static public class Hinting {
                /// <summary>Hint/help sequence begins.</summary>
                public const int StartHint = 2510;
                /// <summary>Hint/help sequence completes naturally.</summary>
                public const int CompleteHint = 2511;
                /// <summary>Hint/help display is cleared or no longer available.</summary>
                public const int ClearHint = 2512;
                /// <summary>Hint/help advances to the next unit.</summary>
                public const int AdvanceHint = 2513;
                /// <summary>Hint/help is skipped to the end.</summary>
                public const int SkipHint = 2514;
                /// <summary>Player requests a hint/help (player-initiated request).</summary>
                public const int RequestHint = 2515;
            }
        }

        static public class Segmentation {

            static public class GlobalGameplaySegments {
                /// <summary>A global gameplay segment begins.</summary>
                public const int StartGlobalSegment = 3000;
                /// <summary>A global gameplay segment ends.</summary>
                public const int EndGlobalSegment = 3001;
                /// <summary>Global gameplay segment exits without completion.</summary>
                public const int AbandonGlobalSegment = 3002;
                /// <summary>Global gameplay segment resumes/restores.</summary>
                public const int ResumeGlobalSegment = 3003;
            }

            static public class ExclusiveTopologicalSegments {
                /// <summary>The current exclusive segment begins (e.g., level start).</summary>
                public const int StartSegmentLevel = 3100;
                /// <summary>The current exclusive segment ends (e.g., level complete/exit).</summary>
                public const int EndSegmentLevel = 3101;
                /// <summary>Exclusive segment exits without completion.</summary>
                public const int AbandonSegmentLevel = 3102;
                /// <summary>Exclusive segment resumes/restores.</summary>
                public const int ResumeSegmentLevel = 3103;
                /// <summary>A subsegment within the exclusive segment begins (e.g., round start).</summary>
                public const int StartSubsegmentRound = 3110;
                /// <summary>A subsegment within the exclusive segment ends.</summary>
                public const int EndSubsegmentRound = 3111;
                /// <summary>Subsegment exits without completion.</summary>
                public const int AbandonSubsegmentRound = 3112;
                /// <summary>Subsegment resumes/restores.</summary>
                public const int ResumeSubsegmentRound = 3113;
            }

            static public class NonExclusiveSegments {
                /// <summary>A non-exclusive segment begins.</summary>
                public const int StartSegmentQuestObjective = 3200;
                /// <summary>A non-exclusive segment ends/completes.</summary>
                public const int EndSegmentQuestObjective = 3201;
                /// <summary>A non-exclusive segment is abandoned.</summary>
                public const int AbandonSegmentQuestObjective = 3202;
                /// <summary>A non-exclusive segment resumes/restores.</summary>
                public const int ResumeSegmentQuestObjective = 3203;
            }

            static public class SpatialRegions {
                /// <summary>Player enters a spatial region/area.</summary>
                public const int EnterRegion = 3300;
                /// <summary>Player exits a spatial region/area.</summary>
                public const int ExitRegion = 3301;
                /// <summary>Region is exited via interruption/quit (without normal exit).</summary>
                public const int AbandonRegion = 3302;
                /// <summary>Player returns to a region via restore/resume.</summary>
                public const int ResumeRegion = 3303;
            }
        }

        static public class PlayerAction {

            static public class UniversalPlayerActions {
                /// <summary>The player submits or commits a response or action.</summary>
                public const int SubmitResponse = 4000;
                /// <summary>The player cancels or withdraws a previously initiated response.</summary>
                public const int CancelSubmission = 4001;
            }

            static public class PuzzleConstructedResponse {
                /// <summary>The player picks up or grabs an object.</summary>
                public const int PickUpObject = 4100;
                /// <summary>The player places an object in a valid location/configuration.</summary>
                public const int PlaceObjectValid = 4101;
                /// <summary>The player attempts to place an object in an invalid location/configuration.</summary>
                public const int PlaceObjectInvalid = 4102;
                /// <summary>The player removes an object from its current placement.</summary>
                public const int RemoveObject = 4103;
                /// <summary>The player begins rotating an object.</summary>
                public const int StartRotateObject = 4104;
                /// <summary>The player finishes rotating an object.</summary>
                public const int EndRotateObject = 4105;
                /// <summary>The player previews a potential object placement.</summary>
                public const int PreviewPlacement = 4106;
                /// <summary>The player modifies an object’s state or configuration.</summary>
                public const int ModifyObject = 4107;
            }

            static public class PointAndClick {
                /// <summary>The player selects an object.</summary>
                public const int SelectObject = 4200;
                /// <summary>The player deselects an object.</summary>
                public const int DeselectObject = 4201;
                /// <summary>The player activates or triggers an object.</summary>
                public const int ActivateObject = 4202;
                /// <summary>The player changes an object’s state through interaction.</summary>
                public const int ChangeObjectState = 4203;
                /// <summary>The player inspects or examines an object.</summary>
                public const int InspectObject = 4204;
                /// <summary>The player applies or uses an object.</summary>
                public const int UseObject = 4205;
                /// <summary>The player begins panning the view.</summary>
                public const int StartPanView = 4206;
                /// <summary>The player ends panning the view.</summary>
                public const int EndPanView = 4207;
            }

            static public class Combat {
                /// <summary>The player selects a combat target.</summary>
                public const int SelectTarget = 4300;
                /// <summary>The player initiates an attack.</summary>
                public const int InitiateAttack = 4301;
                /// <summary>The player performs a defensive action.</summary>
                public const int Defend = 4302;
                /// <summary>The player attempts to evade an attack.</summary>
                public const int Evade = 4303;
                /// <summary>The player uses a combat ability.</summary>
                public const int UseAbility = 4304;
                /// <summary>The player begins aiming.</summary>
                public const int StartAim = 4305;
                /// <summary>The player finishes aiming.</summary>
                public const int EndAim = 4306;
            }

            static public class Navigation {
                /// <summary>The player begins moving.</summary>
                public const int StartMovement = 4400;
                /// <summary>The player stops moving.</summary>
                public const int EndMovement = 4401;
                /// <summary>The player enters a defined area.</summary>
                public const int EnterArea = 4402;
                /// <summary>The player exits a defined area.</summary>
                public const int ExitArea = 4403;
                /// <summary>The player sets a movement destination.</summary>
                public const int SetDestination = 4404;
                /// <summary>The player snaps to a specific location.</summary>
                public const int SnapToLocation = 4405;
                /// <summary>The player advances time.</summary>
                public const int AdvanceTime = 4406;
            }

            static public class ResourceManagement {
                /// <summary>The player purchases a resource or item.</summary>
                public const int Buy = 4500;
                /// <summary>The player sells a resource or item.</summary>
                public const int Sell = 4501;
                /// <summary>The player stores a resource or item.</summary>
                public const int Store = 4502;
                /// <summary>The player collects or acquires a resource.</summary>
                public const int Collect = 4503;
                /// <summary>The player uses or consumes a resource.</summary>
                public const int UseResource = 4504;
                /// <summary>The player loses a resource.</summary>
                public const int LoseResource = 4505;
                /// <summary>The player discards a resource.</summary>
                public const int DiscardResource = 4506;
                /// <summary>The player allocates a resource.</summary>
                public const int AllocateResource = 4507;
                /// <summary>The player converts one resource into another.</summary>
                public const int ConvertResource = 4508;
            }

            static public class Simulation {
                /// <summary>The player assigns an entity or resource.</summary>
                public const int Assign = 4600;
                /// <summary>The player removes an assignment.</summary>
                public const int Unassign = 4601;
                /// <summary>The player sets a priority value.</summary>
                public const int SetPriority = 4602;
                /// <summary>The player adjusts a simulation parameter.</summary>
                public const int AdjustParameter = 4603;
                /// <summary>The player schedules a simulation action.</summary>
                public const int ScheduleAction = 4604;
                /// <summary>The player pauses the simulation.</summary>
                public const int PauseSimulation = 4605;
                /// <summary>The player resumes the simulation.</summary>
                public const int ResumeSimulation = 4606;
                /// <summary>The player requests the current simulation state.</summary>
                public const int RequestCurrentState = 4607;
            }

            static public class InterfaceStructuralNavigation {
                /// <summary>The player selects a segment or subsegment.</summary>
                public const int SelectSegment = 4700;
                /// <summary>The player opens an in-game interface element.</summary>
                public const int OpenInterface = 4701;
                /// <summary>The player closes an in-game interface element.</summary>
                public const int CloseInterface = 4702;
                /// <summary>The player navigates to a different in-game screen.</summary>
                public const int NavigateToScreen = 4703;
                /// <summary>The player returns to the previous in-game screen.</summary>
                public const int ReturnToPreviousScreen = 4704;
                /// <summary>The player selects an interface item.</summary>
                public const int SelectItem = 4705;
                /// <summary>The player confirms a selection.</summary>
                public const int ConfirmSelection = 4706;
                /// <summary>The player cancels a selection.</summary>
                public const int CancelSelection = 4707;
                /// <summary>The player switches views.</summary>
                public const int SwitchView = 4708;
                /// <summary>The player toggles an overlay.</summary>
                public const int ToggleOverlay = 4709;
            }
        }

        static public class OtherHumanPlayerAction {

            static public class PuzzleConstructedResponse {
                /// <summary>Mirrors 4100: The player picks up or grabs an object.</summary>
                public const int PickUpObject = 5100;
                /// <summary>Mirrors 4101: The player places an object in a valid location/configuration.</summary>
                public const int PlaceObjectValid = 5101;
                /// <summary>Mirrors 4102: The player attempts to place an object in an invalid location/configuration.</summary>
                public const int PlaceObjectInvalid = 5102;
                /// <summary>Mirrors 4103: The player removes an object from its current placement.</summary>
                public const int RemoveObject = 5103;
                /// <summary>Mirrors 4104: The player begins rotating an object.</summary>
                public const int StartRotateObject = 5104;
                /// <summary>Mirrors 4105: The player finishes rotating an object.</summary>
                public const int EndRotateObject = 5105;
                /// <summary>Mirrors 4106: The player previews a potential object placement.</summary>
                public const int PreviewPlacement = 5106;
                /// <summary>Mirrors 4107: The player modifies an object’s state or configuration.</summary>
                public const int ModifyObject = 5107;
            }

            static public class PointAndClick {
                /// <summary>Mirrors 4200: The player selects an object.</summary>
                public const int SelectObject = 5200;
                /// <summary>Mirrors 4201: The player deselects an object.</summary>
                public const int DeselectObject = 5201;
                /// <summary>Mirrors 4202: The player activates or triggers an object.</summary>
                public const int ActivateObject = 5202;
                /// <summary>Mirrors 4203: The player changes an object’s state through interaction.</summary>
                public const int ChangeObjectState = 5203;
                /// <summary>Mirrors 4204: The player inspects or examines an object.</summary>
                public const int InspectObject = 5204;
                /// <summary>Mirrors 4205: The player applies or uses an object.</summary>
                public const int UseObject = 5205;
                /// <summary>Mirrors 4206: The player begins panning the view.</summary>
                public const int StartPanView = 5206;
                /// <summary>Mirrors 4207: The player ends panning the view.</summary>
                public const int EndPanView = 5207;
            }

            static public class Combat {
                /// <summary>Mirrors 4300: The player selects a combat target.</summary>
                public const int SelectTarget = 5300;
                /// <summary>Mirrors 4301: The player initiates an attack.</summary>
                public const int InitiateAttack = 5301;
                /// <summary>Mirrors 4302: The player performs a defensive action.</summary>
                public const int Defend = 5302;
                /// <summary>Mirrors 4303: The player attempts to evade an attack.</summary>
                public const int Evade = 5303;
                /// <summary>Mirrors 4304: The player uses a combat ability.</summary>
                public const int UseAbility = 5304;
                /// <summary>Mirrors 4305: The player begins aiming.</summary>
                public const int StartAim = 5305;
                /// <summary>Mirrors 4306: The player finishes aiming.</summary>
                public const int EndAim = 5306;
            }

            static public class Navigation {
                /// <summary>Mirrors 4400: The player begins moving.</summary>
                public const int StartMovement = 5400;
                /// <summary>Mirrors 4401: The player stops moving.</summary>
                public const int EndMovement = 5401;
                /// <summary>Mirrors 4402: The player enters a defined area.</summary>
                public const int EnterArea = 5402;
                /// <summary>Mirrors 4403: The player exits a defined area.</summary>
                public const int ExitArea = 5403;
                /// <summary>Mirrors 4404: The player sets a movement destination.</summary>
                public const int SetDestination = 5404;
                /// <summary>Mirrors 4405: The player snaps to a specific location.</summary>
                public const int SnapToLocation = 5405;
                /// <summary>Mirrors 4406: The player advances time.</summary>
                public const int AdvanceTime = 5406;
            }

            static public class ResourceManagement {
                /// <summary>Mirrors 4500: The player purchases a resource or item.</summary>
                public const int Buy = 5500;
                /// <summary>Mirrors 4501: The player sells a resource or item.</summary>
                public const int Sell = 5501;
                /// <summary>Mirrors 4502: The player stores a resource or item.</summary>
                public const int Store = 5502;
                /// <summary>Mirrors 4503: The player collects or acquires a resource.</summary>
                public const int Collect = 5503;
                /// <summary>Mirrors 4504: The player uses or consumes a resource.</summary>
                public const int UseResource = 5504;
                /// <summary>Mirrors 4505: The player loses a resource.</summary>
                public const int LoseResource = 5505;
                /// <summary>Mirrors 4506: The player discards a resource.</summary>
                public const int DiscardResource = 5506;
                /// <summary>Mirrors 4507: The player allocates a resource.</summary>
                public const int AllocateResource = 5507;
                /// <summary>Mirrors 4508: The player converts one resource into another.</summary>
                public const int ConvertResource = 5508;
            }

            static public class Simulation {
                /// <summary>Mirrors 4600: The player assigns an entity or resource.</summary>
                public const int Assign = 5600;
                /// <summary>Mirrors 4601: The player removes an assignment.</summary>
                public const int Unassign = 5601;
                /// <summary>Mirrors 4602: The player sets a priority value.</summary>
                public const int SetPriority = 5602;
                /// <summary>Mirrors 4603: The player adjusts a simulation parameter.</summary>
                public const int AdjustParameter = 5603;
                /// <summary>Mirrors 4604: The player schedules a simulation action.</summary>
                public const int ScheduleAction = 5604;
                /// <summary>Mirrors 4605: The player pauses the simulation.</summary>
                public const int PauseSimulation = 5605;
                /// <summary>Mirrors 4606: The player resumes the simulation.</summary>
                public const int ResumeSimulation = 5606;
                /// <summary>Mirrors 4607: The player requests the current simulation state.</summary>
                public const int RequestCurrentState = 5607;
            }

            static public class InterfaceStructuralNavigation {
                /// <summary>Mirrors 4700: The player selects a segment or subsegment.</summary>
                public const int SelectSegment = 5700;
                /// <summary>Mirrors 4701: The player opens an in-game interface element.</summary>
                public const int OpenInterface = 5701;
                /// <summary>Mirrors 4702: The player closes an in-game interface element.</summary>
                public const int CloseInterface = 5702;
                /// <summary>Mirrors 4703: The player navigates to a different in-game screen.</summary>
                public const int NavigateToScreen = 5703;
                /// <summary>Mirrors 4704: The player returns to the previous in-game screen.</summary>
                public const int ReturnToPreviousScreen = 5704;
                /// <summary>Mirrors 4705: The player selects an interface item.</summary>
                public const int SelectItem = 5705;
                /// <summary>Mirrors 4706: The player confirms a selection.</summary>
                public const int ConfirmSelection = 5706;
                /// <summary>Mirrors 4707: The player cancels a selection.</summary>
                public const int CancelSelection = 5707;
                /// <summary>Mirrors 4708: The player switches views.</summary>
                public const int SwitchView = 5708;
                /// <summary>Mirrors 4709: The player toggles an overlay.</summary>
                public const int ToggleOverlay = 5709;
            }
        }

        static public class SystemControlledActorAction {

            static public class PuzzleConstructedResponse {
                /// <summary>Mirrors 4100: The player picks up or grabs an object.</summary>
                public const int PickUpObject = 6100;
                /// <summary>Mirrors 4101: The player places an object in a valid location/configuration.</summary>
                public const int PlaceObjectValid = 6101;
                /// <summary>Mirrors 4102: The player attempts to place an object in an invalid location/configuration.</summary>
                public const int PlaceObjectInvalid = 6102;
                /// <summary>Mirrors 4103: The player removes an object from its current placement.</summary>
                public const int RemoveObject = 6103;
                /// <summary>Mirrors 4104: The player begins rotating an object.</summary>
                public const int StartRotateObject = 6104;
                /// <summary>Mirrors 4105: The player finishes rotating an object.</summary>
                public const int EndRotateObject = 6105;
                /// <summary>Mirrors 4106: The player previews a potential object placement.</summary>
                public const int PreviewPlacement = 6106;
                /// <summary>Mirrors 4107: The player modifies an object’s state or configuration.</summary>
                public const int ModifyObject = 6107;
            }

            static public class PointAndClick {
                /// <summary>Mirrors 4200: The player selects an object.</summary>
                public const int SelectObject = 6200;
                /// <summary>Mirrors 4201: The player deselects an object.</summary>
                public const int DeselectObject = 6201;
                /// <summary>Mirrors 4202: The player activates or triggers an object.</summary>
                public const int ActivateObject = 6202;
                /// <summary>Mirrors 4203: The player changes an object’s state through interaction.</summary>
                public const int ChangeObjectState = 6203;
                /// <summary>Mirrors 4204: The player inspects or examines an object.</summary>
                public const int InspectObject = 6204;
                /// <summary>Mirrors 4205: The player applies or uses an object.</summary>
                public const int UseObject = 6205;
                /// <summary>Mirrors 4206: The player begins panning the view.</summary>
                public const int StartPanView = 6206;
                /// <summary>Mirrors 4207: The player ends panning the view.</summary>
                public const int EndPanView = 6207;
            }

            static public class Combat {
                /// <summary>Mirrors 4300: The player selects a combat target.</summary>
                public const int SelectTarget = 6300;
                /// <summary>Mirrors 4301: The player initiates an attack.</summary>
                public const int InitiateAttack = 6301;
                /// <summary>Mirrors 4302: The player performs a defensive action.</summary>
                public const int Defend = 6302;
                /// <summary>Mirrors 4303: The player attempts to evade an attack.</summary>
                public const int Evade = 6303;
                /// <summary>Mirrors 4304: The player uses a combat ability.</summary>
                public const int UseAbility = 6304;
                /// <summary>Mirrors 4305: The player begins aiming.</summary>
                public const int StartAim = 6305;
                /// <summary>Mirrors 4306: The player finishes aiming.</summary>
                public const int EndAim = 6306;
            }

            static public class Navigation {
                /// <summary>Mirrors 4400: The player begins moving.</summary>
                public const int StartMovement = 6400;
                /// <summary>Mirrors 4401: The player stops moving.</summary>
                public const int EndMovement = 6401;
                /// <summary>Mirrors 4402: The player enters a defined area.</summary>
                public const int EnterArea = 6402;
                /// <summary>Mirrors 4403: The player exits a defined area.</summary>
                public const int ExitArea = 6403;
                /// <summary>Mirrors 4404: The player sets a movement destination.</summary>
                public const int SetDestination = 6404;
                /// <summary>Mirrors 4405: The player snaps to a specific location.</summary>
                public const int SnapToLocation = 6405;
                /// <summary>Mirrors 4406: The player advances time.</summary>
                public const int AdvanceTime = 6406;
            }

            static public class ResourceManagement {
                /// <summary>Mirrors 4500: The player purchases a resource or item.</summary>
                public const int Buy = 6500;
                /// <summary>Mirrors 4501: The player sells a resource or item.</summary>
                public const int Sell = 6501;
                /// <summary>Mirrors 4502: The player stores a resource or item.</summary>
                public const int Store = 6502;
                /// <summary>Mirrors 4503: The player collects or acquires a resource.</summary>
                public const int Collect = 6503;
                /// <summary>Mirrors 4504: The player uses or consumes a resource.</summary>
                public const int UseResource = 6504;
                /// <summary>Mirrors 4505: The player loses a resource.</summary>
                public const int LoseResource = 6505;
                /// <summary>Mirrors 4506: The player discards a resource.</summary>
                public const int DiscardResource = 6506;
                /// <summary>Mirrors 4507: The player allocates a resource.</summary>
                public const int AllocateResource = 6507;
                /// <summary>Mirrors 4508: The player converts one resource into another.</summary>
                public const int ConvertResource = 6508;
            }

            static public class Simulation {
                /// <summary>Mirrors 4600: The player assigns an entity or resource.</summary>
                public const int Assign = 6600;
                /// <summary>Mirrors 4601: The player removes an assignment.</summary>
                public const int Unassign = 6601;
                /// <summary>Mirrors 4602: The player sets a priority value.</summary>
                public const int SetPriority = 6602;
                /// <summary>Mirrors 4603: The player adjusts a simulation parameter.</summary>
                public const int AdjustParameter = 6603;
                /// <summary>Mirrors 4604: The player schedules a simulation action.</summary>
                public const int ScheduleAction = 6604;
                /// <summary>Mirrors 4605: The player pauses the simulation.</summary>
                public const int PauseSimulation = 6605;
                /// <summary>Mirrors 4606: The player resumes the simulation.</summary>
                public const int ResumeSimulation = 6606;
                /// <summary>Mirrors 4607: The player requests the current simulation state.</summary>
                public const int RequestCurrentState = 6607;
            }

            static public class InterfaceStructuralNavigation {
                /// <summary>Mirrors 4700: The player selects a segment or subsegment.</summary>
                public const int SelectSegment = 6700;
                /// <summary>Mirrors 4701: The player opens an in-game interface element.</summary>
                public const int OpenInterface = 6701;
                /// <summary>Mirrors 4702: The player closes an in-game interface element.</summary>
                public const int CloseInterface = 6702;
                /// <summary>Mirrors 4703: The player navigates to a different in-game screen.</summary>
                public const int NavigateToScreen = 6703;
                /// <summary>Mirrors 4704: The player returns to the previous in-game screen.</summary>
                public const int ReturnToPreviousScreen = 6704;
                /// <summary>Mirrors 4705: The player selects an interface item.</summary>
                public const int SelectItem = 6705;
                /// <summary>Mirrors 4706: The player confirms a selection.</summary>
                public const int ConfirmSelection = 6706;
                /// <summary>Mirrors 4707: The player cancels a selection.</summary>
                public const int CancelSelection = 6707;
                /// <summary>Mirrors 4708: The player switches views.</summary>
                public const int SwitchView = 6708;
                /// <summary>Mirrors 4709: The player toggles an overlay.</summary>
                public const int ToggleOverlay = 6709;
            }
        }

        static public class SystemAction {

            static public class EntityResourceChanges {
                /// <summary>The system introduces a new entity into active gameplay.</summary>
                public const int CreateEntity = 7110;
                /// <summary>The system removes an entity from active gameplay.</summary>
                public const int RemoveEntity = 7111;
                /// <summary>The system changes an entity’s form, type, or role while preserving continuity within gameplay.</summary>
                public const int TransformEntity = 7112;
                /// <summary>The system increases the value of a gameplay resource.</summary>
                public const int IncrementResource = 7120;
                /// <summary>The system decreases the value of a gameplay resource.</summary>
                public const int DecrementResource = 7121;
                /// <summary>The system advances or updates a counter or timer variable.</summary>
                public const int UpdateCounter = 7122;
            }

            static public class MovementSpatialChange {
                /// <summary>The system initiates continuous movement of an entity.</summary>
                public const int StartEntityMovement = 7200;
                /// <summary>The system ends continuous movement of an entity.</summary>
                public const int EndEntityMovement = 7201;
                /// <summary>The system instantly relocates an entity to a new position.</summary>
                public const int RepositionEntity = 7202;
                /// <summary>The system initiates movement of an environmental gameplay element.</summary>
                public const int StartEnvironmentMovement = 7203;
                /// <summary>The system ends movement of an environmental gameplay element.</summary>
                public const int EndEnvironmentMovement = 7204;
                /// <summary>The system instantly relocates an environmental gameplay element.</summary>
                public const int RepositionEnvironmentElement = 7205;
            }

            static public class SimulationExecution {
                /// <summary>The system initializes a simulation process.</summary>
                public const int InitializeSimulation = 7300;
                /// <summary>The system begins executing a simulation.</summary>
                public const int StartSimulation = 7301;
                /// <summary>The system pauses simulation execution.</summary>
                public const int PauseSimulation = 7302;
                /// <summary>The system resumes a paused simulation.</summary>
                public const int ResumeSimulation = 7303;
                /// <summary>The system advances the simulation by a discrete step or interval.</summary>
                public const int AdvanceSimulation = 7304;
                /// <summary>The system resets the simulation to a baseline state.</summary>
                public const int ResetSimulation = 7305;
                /// <summary>The system terminates simulation execution.</summary>
                public const int TerminateSimulation = 7306;
            }

            static public class InformationVisibility {
                /// <summary>The system makes gameplay-relevant information visible or discoverable to the player.</summary>
                public const int RevealInformation = 7400;
                /// <summary>The system hides gameplay-relevant information from the player.</summary>
                public const int ConcealInformation = 7401;
            }

            static public class InGameInterfaceState {
                /// <summary>The system displays an in-game interface element.</summary>
                public const int DisplayInterfaceElement = 7500;
                /// <summary>The system hides an in-game interface element.</summary>
                public const int HideInterfaceElement = 7501;
                /// <summary>The system updates the content or state of an interface element.</summary>
                public const int UpdateInterfaceElement = 7502;
                /// <summary>The system enables interaction with an interface element.</summary>
                public const int EnableInterfaceElement = 7503;
                /// <summary>The system disables interaction with an interface element.</summary>
                public const int DisableInterfaceElement = 7504;
            }

            static public class SystemSignaling {
                /// <summary>The system begins emitting a gameplay-relevant audiovisual signal.</summary>
                public const int StartSystemSignal = 7600;
                /// <summary>The system stops emitting a gameplay-relevant audiovisual signal.</summary>
                public const int EndSystemSignal = 7601;
                /// <summary>The system changes the type or state of an active signal.</summary>
                public const int ChangeSystemSignal = 7602;
            }
        }
    }
}
